"""The release job installs the signing step's dependencies from `uv export --hashes`, cut down to what
`cryptography` needs: `packaging/signing_requirements.py` does the cutting, and these pin that it keeps
exactly that closure, hashes and all."""
from __future__ import annotations

import importlib.util
import shutil
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / "packaging" / "signing_requirements.py"

LOCK = """
version = 1

[[package]]
name = "cryptography"
version = "50.0.2"
dependencies = [
    { name = "cffi", marker = "platform_python_implementation != 'PyPy'" },
]

[[package]]
name = "cffi"
version = "2.1.1"
dependencies = [
    { name = "pycparser", marker = "implementation_name != 'PyPy'" },
]

[[package]]
name = "pycparser"
version = "3.0"

[[package]]
name = "httpx"
version = "0.28.1"
dependencies = [{ name = "anyio" }]

[[package]]
name = "anyio"
version = "4.0"
"""

EXPORT = """# This file was autogenerated by uv via the following command:
#    uv export --frozen --no-emit-project --no-dev
anyio==4.0 \\
    --hash=sha256:aaaa
    # via httpx
cffi==2.1.1 ; platform_python_implementation != 'PyPy' \\
    --hash=sha256:bbbb \\
    --hash=sha256:cccc
    # via cryptography
cryptography==50.0.2 \\
    --hash=sha256:dddd
httpx==0.28.1 \\
    --hash=sha256:eeee
pycparser==3.0 ; implementation_name != 'PyPy' \\
    --hash=sha256:ffff
    # via cffi
"""


def load():
    spec = importlib.util.spec_from_file_location("signing_requirements", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_only_cryptography_and_what_it_needs_are_kept(tmp_path: Path):
    lock = tmp_path / "uv.lock"
    lock.write_text(LOCK)
    out = load().filter_export(EXPORT, lock, "cryptography")

    assert "anyio" not in out and "httpx" not in out
    assert "cryptography==50.0.2 \\\n    --hash=sha256:dddd" in out
    assert "cffi==2.1.1 ; platform_python_implementation != 'PyPy' \\\n    --hash=sha256:bbbb \\\n" in out
    assert "pycparser==3.0" in out and "--hash=sha256:ffff" in out


def test_a_package_missing_from_the_export_fails_loudly(tmp_path: Path):
    lock = tmp_path / "uv.lock"
    lock.write_text(LOCK)
    with pytest.raises(SystemExit):
        load().filter_export(EXPORT.replace("pycparser==3.0", "pycparserx==3.0"), lock, "cryptography")


def test_every_kept_requirement_carries_a_hash(tmp_path: Path):
    lock = tmp_path / "uv.lock"
    lock.write_text(LOCK)
    with pytest.raises(SystemExit):
        load().filter_export(EXPORT.replace("cryptography==50.0.2 \\\n    --hash=sha256:dddd\n",
                                            "cryptography==50.0.2\n"), lock, "cryptography")


@pytest.mark.skipif(shutil.which("uv") is None, reason="uv not on PATH")
def test_the_real_lock_gives_cryptography_and_its_closure():
    export = subprocess.run(["uv", "export", "--frozen", "--no-emit-project", "--no-dev", "--format",
                             "requirements-txt"], cwd=ROOT, capture_output=True, text=True, check=True).stdout
    out = load().filter_export(export, ROOT / "uv.lock", "cryptography")
    names = sorted(line.split("==")[0] for line in out.splitlines() if "==" in line)
    assert names == ["cffi", "cryptography", "pycparser"]
