# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the Windows app. Build it with `packaging/build_windows.ps1`, not by hand -- the
icon and the helper programs have to be in packaging/build first and this file refuses to run without
them.

The Windows twin of Flackey.spec, and deliberately the same in everything that is not about Windows:
the same datas, the same uvicorn imports, and the same things left out (`.env` and any settings file,
because they carry the owner's own Telegram credentials and this build is made to hand to someone else).

A onedir build, not onefile: onefile unpacks ~100 MB into %TEMP% on every launch, which is slow, trips
antivirus heuristics, and leaves the Inno Setup installer nothing stable to install.
"""

import re
from pathlib import Path

from PyInstaller.utils.hooks import collect_data_files, collect_submodules
from PyInstaller.utils.win32.versioninfo import (
    FixedFileInfo,
    StringFileInfo,
    StringStruct,
    StringTable,
    VarFileInfo,
    VarStruct,
    VSVersionInfo,
)

ROOT = Path(SPECPATH).parent  # noqa: F821 - SPECPATH is injected by PyInstaller
# encoding spelled out: on Windows the default is the ANSI code page, and the build must not depend on
# the machine's locale.
VERSION = re.search(
    r'^__version__ = "([^"]+)"',
    (ROOT / "src" / "flackey" / "__init__.py").read_text(encoding="utf-8"),
    re.M,
).group(1)

datas = [
    # `resource_dir()` resolves to the unpacked bundle when frozen, so these two land exactly where
    # `UI_DIR` and `APP_ICON` look for them.
    (str(ROOT / "web" / "dist"), "web/dist"),
    (str(ROOT / "src" / "flackey" / "assets"), "flackey/assets"),
]
datas += collect_data_files("curl_cffi")   # the bundled CA bundle; without it every HTTPS call fails

# The helper programs `flackey.tools` looks for first: `bundled_bin_dir()` is `sys._MEIPASS / "bin"`, and
# a destination of "bin" here is exactly that folder. build_windows.ps1 fetches them; a spec run without
# them would build an app that finds no ffmpeg at all on a stock Windows machine, so it refuses.
HELPERS = ROOT / "packaging" / "build" / "bin"
HELPER_NAMES = ("ffmpeg.exe", "ffprobe.exe", "fpcalc.exe")
binaries = [(str(HELPERS / name), "bin") for name in HELPER_NAMES if (HELPERS / name).is_file()]
if len(binaries) != len(HELPER_NAMES):
    raise SystemExit("helper binaries missing from packaging/build/bin: run packaging/build_windows.ps1, not pyinstaller directly")
datas.append((str(HELPERS / "licenses"), "bin/licenses"))

# Generated by build_windows.ps1 from src/flackey/assets/app-icon.png. A file of its own rather than
# PyInstaller's on-the-fly PNG conversion because Inno Setup needs the same .ico for Setup.exe and the
# uninstall entry, and the conversion needs Pillow, which is a build tool here and not part of the app.
ICON = ROOT / "packaging" / "build" / "Flackey.ico"
if not ICON.is_file():
    raise SystemExit(f"{ICON} missing: run packaging/build_windows.ps1, not pyinstaller directly")

# uvicorn picks its loop and protocol implementations by string at run time, so the module graph cannot
# see them and they have to be named. This is the classic way a frozen server starts and then does
# nothing at all.
hiddenimports = collect_submodules("uvicorn") + [
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan.on",
]
# pywebview chooses its backend at run time (`webview.guilib.initialize`). The DLLs are already covered:
# pywebview ships a PyInstaller hook that collects webview/lib (the WebView2 loader and WinForms
# interop), and pyinstaller-hooks-contrib's hook-clr / hook-clr_loader collect Python.Runtime.dll and
# the clr_loader runtime. What is named here is the Python side, so a refactor inside pywebview that
# turns an import into a string cannot quietly produce a window-less build.
hiddenimports += [
    "webview.platforms.winforms",
    "webview.platforms.edgechromium",
    "webview.platforms.win32",
    "clr",
    "clr_loader",
]

a = Analysis(  # noqa: F821
    [str(ROOT / "packaging" / "launch.py")],
    pathex=[str(ROOT / "src")],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    # Nothing in the app draws a chart; matplotlib and tkinter arrive as transitive suggestions and cost
    # tens of megabytes each in a bundle that someone has to download. PIL stays out as on the Mac: the
    # icon conversion that needs it happens before this spec runs.
    excludes=["tkinter", "matplotlib", "PIL", "pytest"],
    noarchive=False,
)
pyz = PYZ(a.pure)  # noqa: F821


# The version resource: what Explorer's Properties > Details tab and the SmartScreen prompt show. An
# unsigned exe with none reads as "Unknown" everywhere; with one it at least says what it is. The fixed
# part wants four integers, and release versions are plain X.Y.Z (check_version.sh enforces it).
def _four(version: str) -> tuple[int, int, int, int]:
    parts = [int(p) for p in re.findall(r"\d+", version)[:4]]
    return tuple(parts + [0] * (4 - len(parts)))


version_info = VSVersionInfo(
    ffi=FixedFileInfo(filevers=_four(VERSION), prodvers=_four(VERSION)),
    kids=[
        StringFileInfo([
            # 0409 = US English, 04B0 = Unicode: the pair Windows looks up first.
            StringTable("040904B0", [
                StringStruct("CompanyName", "Flackey"),
                StringStruct("FileDescription", "Flackey"),
                StringStruct("FileVersion", VERSION),
                StringStruct("InternalName", "Flackey"),
                StringStruct("LegalCopyright", "MIT License"),
                StringStruct("OriginalFilename", "Flackey.exe"),
                StringStruct("ProductName", "Flackey"),
                StringStruct("ProductVersion", VERSION),
            ]),
        ]),
        VarFileInfo([VarStruct("Translation", [0x0409, 0x04B0])]),
    ],
)

exe = EXE(  # noqa: F821
    pyz, a.scripts, [],
    exclude_binaries=True,
    name="Flackey",
    debug=False,
    strip=False,
    # UPX-packed executables are a classic antivirus false positive, and an unsigned app has no
    # reputation to spend on one.
    upx=False,
    console=False,   # a windowed build: no console window, stdout goes nowhere, so launch.py logs to a file
    icon=str(ICON),
    version=version_info,
    target_arch=None,
)
coll = COLLECT(  # noqa: F821
    exe, a.binaries, a.datas,
    strip=False, upx=False, name="Flackey",
)
